# Week 1 [Lecture Notebook](https://lantmztlcdtszyrzyefsog.hub.coursera-notebooks.org/user/lantmztlcdtszyrzyefsog/notebooks/Week%201.ipynb)

---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

## The Python Programming Language: Functions

In [117]:
x = 1
y = 2
x + y

3

In [118]:
x

1

In [119]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [120]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z
    
print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


In [121]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true
3


In [122]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

3

<br>

## The Python Programming Language: Types and Sequences

In [123]:
type('This is a string')

str

In [124]:
type(None)

NoneType

In [125]:
type(1)

int

In [126]:
type(1.0)

float

In [127]:
type(add_numbers)

function

### Tuples are an immutable data structure.

In [128]:
# Tuples are enclosed in parentheses.
x = (1, 'a', 2, 'b')
type(x)

tuple

### Lists are a mutable data structure.

In [129]:
# Lists are enclosed in brackets.
x = [1, 'a', 2, 'b']
type(x)

list

In [130]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


In [131]:
for item in x:
    print(item)

1
a
2
b
3.3


In [132]:
i = 0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


In [133]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [134]:
[1] * 3

[1, 1, 1]

In [135]:
1 in [1, 2, 3]

True

### Use bracket notation to slice a string.

In [136]:
x = 'This is a string'
print(x[0])    # first character
print(x[0:1])  # first character with the end character set explicitly
print(x[0:2])  # first two characters

T
T
Th


In [137]:
x[-1]

'g'

In [138]:
x[-4:-2]

'ri'

In [139]:
x[:3]

'Thi'

In [140]:
x[3:]

's is a string'

In [141]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname * 3)
print('Chris' in firstname)

Christopher Brooks
ChristopherChristopherChristopher
True


In [142]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element in the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element in the list
print(firstname)
print(lastname)

Christopher
Brooks


In [143]:
# Make sure you convert objects to strings before concatenating.
"""
'Chris' + 2

>>> TypeError: Can't convert 'int' object to str implicitly
"""

"\n'Chris' + 2\n\n>>> TypeError: Can't convert 'int' object to str implicitly\n"

In [144]:
'Chris' + str(2)

'Chris2'

### Dictionaries associate keys with values.

In [145]:
x = {'Christopher Brooks': 'brooks@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator

'brooks@umich.edu'

In [146]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

In [147]:
for name in x:
    print(x[name])

billg@microsoft.com
None
brooks@umich.edu


In [148]:
for email in x.values():
    print(email)

billg@microsoft.com
None
brooks@umich.edu


In [149]:
for name, email in x.items():
    print(name)
    print(email)

Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None
Christopher Brooks
brooks@umich.edu


In [150]:
# You can unpack a sequence into different variables:
x = ('Christopher', 'Brooks', 'brooksch@mich.edu')
fname, lname, email = x

In [151]:
fname

'Christopher'

In [152]:
lname

'Brooks'

In [153]:
email

'brooksch@mich.edu'

In [154]:
# Make sure that the number of values you are unpacking matches the number of variables being assigned:
"""
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

>>> 2 fname, lname, email = x
>>> ValueError: too many values to unpack (expected 3)
"""

"\nx = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')\nfname, lname, email = x\n\n>>> 2 fname, lname, email = x\n>>> ValueError: too many values to unpack (expected 3)\n"

## The Python Programming Language: More on Strings

In [155]:
"""
print('Chris' + 2)

>>> TypeError: Can't convert 'int' object to str implicitly
"""

"\nprint('Chris' + 2)\n\n>>> TypeError: Can't convert 'int' object to str implicitly\n"

In [156]:
print('Chris' + str(2))

Chris2


In [157]:
# Python has string formatting built in:
sales_record = {
    'price': 3.24,
    'num_items': 4,
    'person': 'Chris'
}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}.'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items'] * sales_record['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96.


## Reading and Writing CSV Files

In [158]:
# We are going to use the mpg.csv dataset that contains fuel economy data for 234 cars.
import csv
# floating-point precision to 2 decimal places
%precision 2  

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
# print(mpg[:3])  # prints the first 3 dictionaries in the list
mpg[:3]  # is easier to read than the print statement output

[{'': '1',
  'class': 'compact',
  'cty': '18',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'auto(l5)',
  'year': '1999'},
 {'': '2',
  'class': 'compact',
  'cty': '21',
  'cyl': '4',
  'displ': '1.8',
  'drv': 'f',
  'fl': 'p',
  'hwy': '29',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m5)',
  'year': '1999'},
 {'': '3',
  'class': 'compact',
  'cty': '20',
  'cyl': '4',
  'displ': '2',
  'drv': 'f',
  'fl': 'p',
  'hwy': '31',
  'manufacturer': 'audi',
  'model': 'a4',
  'trans': 'manual(m6)',
  'year': '2008'}]

In [159]:
# csv.Dictreader has read in each row of our csv file as a dictionary.
# len() shows that our list is comprised of 234 dictionaries -- one for each car.
len(mpg)

234

In [160]:
# keys() gives us the column names of our csv file.
mpg[0].keys()

dict_keys(['', 'cyl', 'trans', 'manufacturer', 'class', 'displ', 'drv', 'year', 'fl', 'cty', 'hwy', 'model'])

In [161]:
# Let's find the average city ('cty) fuel economy for all cars.
# All values in the dictionaries are strings, so we need to convert them to floats.

sum(float(entry['cty']) for entry in mpg) / len(mpg)

16.86

In [162]:
# Now let's find the average highway ('hwy') fuel economy for all cars:

sum(float(entry['hwy']) for entry in mpg) / len(mpg)

23.44

In [163]:
# We can use set() to return the unique values for the number of cylinders each car has:

cylinders = set(entry['cyl'] for entry in mpg)
cylinders

{'4', '5', '6', '8'}

In [164]:
# Now for something a bit more challenging.
# We are grouping the cars by number of cylinders, and finding the average city mpg for each group.

CityMpgByCyl = []

for c in cylinders:  # iterate over all of the cylinder levels
    sum_mpg = 0
    cyl_type_count = 0
    for car in mpg:  # iterate over all of the dictionaries
        if car['cyl'] == c:  # if the cylinder level type matches,
            sum_mpg += float(car['cty'])  # add the city mpg
            cyl_type_count += 1  # increment the count
    CityMpgByCyl.append((c, sum_mpg / cyl_type_count))  # append the tuple ('cylinder', 'avg mpg')
    
CityMpgByCyl.sort(key=lambda x: x[0])  # sort lowest to highest
CityMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [165]:
# Use set() to return the unique values for the class types in our dataset.

vehicleclass = set(car['class'] for car in mpg)
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [166]:
# Now let's find the average highway mpg for each class of vehicle in our dataset.

HwyMpgByClass = []

for kind in vehicleclass:  # iterate over all of the vehicle classes
    sum_mpg = 0
    vehicle_class_count = 0
    for car in mpg:  # iterate over all of the dictionaries
        if car['class'] == kind:  # if the cylinder amount type matches,
            sum_mpg += float(car['hwy'])  # add the highway mpg
            vehicle_class_count += 1  # increment the count
    HwyMpgByClass.append((kind, sum_mpg / vehicle_class_count))  # append the tuple ('class', 'avg mpg')
    
HwyMpgByClass.sort(key=lambda x: x[1])  # sort lowest to highest
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

## The Python Programming Language: Dates and Times

In [167]:
# Pandas has a datetime library -- I guess we'll go over that later.
import datetime as dt
# https://docs.python.org/3.5/library/datetime.html#module-datetime
import time as tm
# https://docs.python.org/3.5/library/time.html

In [168]:
# time() returns the current time in seconds since the Epoch (January 1st 1970).
tm.time()

1478126838.98

In [169]:
# Convert the timestamp to datetime.
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2016, 11, 2, 15, 47, 18, 987043)

In [170]:
# Here are some handy datetime attributes:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second

(2016, 11, 2, 15, 47, 18)

In [171]:
# timedelta() is a duration expressing the difference between two dates.
delta = dt.timedelta(days = 100)
delta

datetime.timedelta(100)

In [172]:
# Guess what date.today() does.
today = dt.date.today()
today

datetime.date(2016, 11, 2)

In [173]:
minus100 = today - delta
minus100

datetime.date(2016, 7, 25)

In [174]:
today > minus100

True

## The Python Programming Language: Objects and map()

In [175]:
# An example of a class in Python:
class Person:
    department = 'School of Information'  # a class variable
    
    def set_name(self, new_name):  # a method
        self.name = new_name
        
    def set_location(self, new_location):
        self.location = new_location

In [176]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} lives in {} and works in the {}.'.format(person.name, person.location, person.department))

Christopher Brooks lives in Ann Arbor, MI, USA and works in the School of Information.


In [177]:
# Here is an example of mapping the min() function between two lists:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

In [178]:
# Now we can iterate through the map object to see the values:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


## The Python Programming Language: Lambdas and List Comprehensions

In [179]:
# Here is an example of a lambda that takes in three parameters and adds the first two:
my_function = lambda a, b, c : a + b

In [180]:
my_function(1, 2, 3)

3

In [181]:
# Return all even numbers from 0 to 999:
my_list = []
for number in range(0, 1000):  # range(1000) also works
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [182]:
# Now let's do the same thing with a list comprehension:
my_list = [number for number in range(0, 1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

### [Here](http://treyhunner.com/2015/12/python-list-comprehensions-now-in-color/) is a nifty post about list comprehensions that can give a better idea about how they work.

<br>

## The Python Programming Language: Numerical Python -- NumPy

In [183]:
import numpy as np

<br>

### Creating Arrays

In [184]:
# Create a list and convert it to a numpy array
mylist = [1, 2, 3]
x = np.array(mylist)
print(mylist)
print(x)
x

[1, 2, 3]
[1 2 3]


array([1, 2, 3])

In [185]:
# You can also pass in a list directly:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [186]:
# Pass in a list of lists to create a multidimensional array.
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [187]:
# Use the shape method to find the dimensions of the array in (rows, columns).
m.shape

(2, 3)

In [188]:
# arange() returns evenly spaced values within a given interval (start, stop, step).
n = np.arange(0, 30, 2)  # start at 0, stop at 29, count up by 2 
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [189]:
# reshape() returns an array containing the same data but with a new shape in (rows, columns).
n = n.reshape(3, 5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [190]:
# linspace() returns evenly spaced numbers over a specified interval (start, stop_num, number_of_nums).
o = np.linspace(0, 4, 9)  # return 9 evenly spaced values from 0 to 4
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [191]:
# resize() changes the shape and size of an array in-place (rows, columns).
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [192]:
# ones() returns a new array of given shape and type, filled with ones (rows, cloumns).
np.ones((3, 2))

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [193]:
# zeros() returns a new array of given shape and type, filled with ones (rows, cloumns).
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [194]:
# eye() returns a 2-D array with ones on the diagonal and zeros elsewhere. 
# https://en.wikipedia.org/wiki/Identity_matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [195]:
# diag() extracts a diagonal or constructs a diagonal array.
np.diag(y)  # y = np.array([4, 5, 6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [196]:
# Create an array using a repeating list (or see https://docs.scipy.org/doc/numpy/reference/generated/numpy.tile.html).
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [197]:
# Repeat elements of an array using repeat() (array, num_repetitions)
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combining Arrays

In [198]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [199]:
# Use vstack() to stack arrays in a sequence vertically (row wise).
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [200]:
# Use hstack() to stack arrays in sequence horizontally (column wise).
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

### Operations
<p>Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and exponentiation.</p>

In [201]:
print(x + y)  # element-wise addition     [1 2 3] + [4 5 6] = [5 7 9]
print(x - y)  # element-wise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [202]:
print(x * y)  # element-wise multiplication  [1 2 3] * [4 5 6] = [4 10 18]
print(x / y)  # element-wise division        [1 2 3] / [4 5 6] = [0.25 0.4 0.5]

[ 4 10 18]
[ 0.25  0.4   0.5 ]


In [203]:
print(x**2)  # element-wise exponentiation  [1 2 3] ^2 =  [1 4 9]
print(x**y)  # element-wise exponentiation  [1 2 3] ^ [4 5 6] = [  1  32 729]

[1 4 9]
[  1  32 729]


<br>
### [Dot Product:](https://en.wikipedia.org/wiki/Dot_product)
<br>
$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [204]:
x.dot(y)  # dot product  1*4 + 2*5 + 3*6

32

In [205]:
z = np.array([y, y**2])
print(len(z))  # number of rows in the array
z

2


array([[ 4,  5,  6],
       [16, 25, 36]])

In [206]:
# Transposing arrays -- transposing permutes the dimensions of the array (swaps rows with columns and vice versa).
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [207]:
# The shape of array z is (2, 3) before transposition.
z.shape

(2, 3)

In [208]:
# Use .T to get the transpose.
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [209]:
# The number of rows has swapped with the number of columns.
z.T.shape

(3, 2)

In [210]:
# Use .dtype to see the data type of the elements in the array.
print(z.dtype)
z

int64


array([[ 4,  5,  6],
       [16, 25, 36]])

In [211]:
# Use .astype() to cast to a specific type.
z = z.astype('f')
print(z.dtype)
z

float32


array([[  4.,   5.,   6.],
       [ 16.,  25.,  36.]], dtype=float32)

<br>
### Math Functions
<p>NumPy has many built-in math functions that can be performed on arrays.</p>

In [212]:
a = np.array([-4, -2, 1, 3, 5])
a

array([-4, -2,  1,  3,  5])

In [213]:
a.sum()

3

In [214]:
a.max()

5

In [216]:
a.min()

-4

In [217]:
a.mean()

0.60

In [218]:
a.std()

3.26

In [220]:
# argmax() and argmin() return the index of the max and min values in an array.
print(a.argmax())
print(a.argmin())

4
0


<br>
### Indexing / Slicing

In [222]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [223]:
# Use bracket notation to get the value at a specific index.
# Remember that in Python, indexing starts at 0.
s[0], s[4], s[-1]

(0, 16, 144)

In [224]:
# Use : to indicate a range.array[start:stop]
# Leaving start or stop empty will default to the [beginning:end] of the array.
s[1:5]

array([ 1,  4,  9, 16])

In [226]:
# Use negatives to count from the back.
s[-4:]

array([ 81, 100, 121, 144])

In [227]:
# A second : can be used to indicate step-size -- array[start:stop:step-size]
# Here we are starting at the 5th element from the end and counting backwards
# by 2 until the beginning of the array is reached.
s[-5::-2]

array([64, 36, 16,  4,  0])

In [228]:
# Let's look at a multidimensional array.
r = np.arange(36)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [229]:
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [230]:
# Use bracket notation to slice -- array[row, column]
r[2, 2]

14

In [231]:
# You can also use : to select a range of rows or columns.
r[3, 3:6]

array([21, 22, 23])

In [232]:
# Here we are selecting all rows up to (but not including) row 2
# and all columns up to (but not including) the last column.
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [233]:
# This is a slice of the last row, and only every other element.
r[-1, ::2]

array([30, 32, 34])

In [234]:
# We can also perform conditional indexing.
# Here we are selecting values from the array that are greater than 30. (Also see np.where)
r[r > 30]

array([31, 32, 33, 34, 35])

In [235]:
# Here we are assigning all values in the array that are greater than 30 to the value of 30.
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
### Copying Data

In [237]:
# Be careful with copying and modifying arrays in NumPy.
# r2 is a slice of r.
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [238]:
# Set this slice's value to zero.
# [:] selects the entire array.
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [239]:
# r has also been changed.
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [241]:
# To avoid this, use r.copy() to create a duplicate array that won't change the original.
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [242]:
# Now, when r_copy is modified, r will not be changed.
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

In [243]:
# Create a new 4 by 3 array of random numbers 0-9.
test = np.random.randint(0, 10, (4, 3))
test

array([[7, 9, 0],
       [4, 6, 2],
       [9, 1, 7],
       [6, 8, 3]])

In [244]:
# Iterate by row.
for row in test:
    print(row)

[7 9 0]
[4 6 2]
[9 1 7]
[6 8 3]


In [245]:
# Iterate by index.
for i in range(len(test)):
    print(test[i])

[7 9 0]
[4 6 2]
[9 1 7]
[6 8 3]


In [246]:
# Iterate by row and index.
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [7 9 0]
row 1 is [4 6 2]
row 2 is [9 1 7]
row 3 is [6 8 3]


In [247]:
# Use zip() to iterate over multiple iterables.
test2 = test**2
test2

array([[49, 81,  0],
       [16, 36,  4],
       [81,  1, 49],
       [36, 64,  9]])

In [248]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[7 9 0] + [49 81  0] = [56 90  0]
[4 6 2] + [16 36  4] = [20 42  6]
[9 1 7] + [81  1 49] = [90  2 56]
[6 8 3] + [36 64  9] = [42 72 12]
